spring.application.name=nativesoundbackend


tts.provider=local
tts.base-url=http://localhost:8000
tts.connect-timeout-ms=5000
tts.read-timeout-ms=10000
tts.max-text-chars=3000
tts.allowed-langs=en,pt,es,de
tts.api-key=${TTS_API_KEY}
